# Generated by Django 3.0.4 on 2020-04-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_covid1'),
    ]

    operations = [
        migrations.CreateModel(
            name='technews',
            fields=[
                ('headlines', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2500)),
                ('hyperlink', models.URLField(max_length=2000)),
                ('source', models.CharField(max_length=2000)),
            ],
        ),
    ]
