# Generated by Django 3.0.4 on 2020-04-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_technews'),
    ]

    operations = [
        migrations.CreateModel(
            name='fullmore',
            fields=[
                ('headlines', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2500)),
                ('hyperlink', models.URLField(max_length=2000)),
                ('source', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='sportsnews',
            fields=[
                ('headlines', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2500)),
                ('hyperlink', models.URLField(max_length=2000)),
                ('source', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='weatherdetails',
            fields=[
                ('city', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('temperature', models.CharField(max_length=2500)),
                ('pressure', models.CharField(max_length=2000)),
                ('humidity', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='worldnews',
            fields=[
                ('headlines', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2500)),
                ('hyperlink', models.URLField(max_length=2000)),
                ('source', models.CharField(max_length=2000)),
            ],
        ),
    ]
